ERROR - 2018-02-27 02:46:08 --> 404 Page Not Found: Faviconico/index
ERROR - 2018-02-27 02:46:48 --> Severity: Error --> Call to undefined method Model_account::loadDbPlatform() C:\xampp\htdocs\Gmedia\app\models\backend\user-management\Model_account.php 13
ERROR - 2018-02-27 02:59:45 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270259453669', '1', 'user-management/privilege_menu', 'Save', '{\\\"id\\\":\\\"\\\",\\\"name\\\":\\\"cihuy\\\",\\\"description\\\":\\\"cihuy\\\",\\\"url\\\":\\\"chiu\\\",\\\"icon\\\":\\\"icon-bubbles\\\",\\\"parent\\\":\\\"0\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Saving Data\\\",\\\"message\\\":\\\"Data has been saved.\\\"}', '::1', '1', '2018-02-27 02:59:45')
ERROR - 2018-02-27 02:59:55 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 C:\xampp\htdocs\Gmedia\sys_ci_3.0\database\drivers\mysqli\mysqli_driver.php 135
ERROR - 2018-02-27 02:59:55 --> Unable to connect to the database
ERROR - 2018-02-27 03:00:44 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270300439698', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"34\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:00:43')
ERROR - 2018-02-27 03:00:49 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270300493185', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"34\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"2\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:00:49')
ERROR - 2018-02-27 03:02:03 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270302030583', '1', 'user-management/privilege_menu', 'Delete', '{\\\"id\\\":\\\"34\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:02:03')
ERROR - 2018-02-27 03:20:41 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270320417102', '1', 'user-management/privilege_menu', 'Delete', '{\\\"id\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:20:41')
ERROR - 2018-02-27 03:21:04 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270321048776', '1', 'user-management/privilege_menu', 'Update', '{\\\"id\\\":\\\"12\\\",\\\"name\\\":\\\"Employees\\\",\\\"description\\\":\\\"Manage Employees\\\",\\\"url\\\":\\\"user-management\\\\/employees\\\",\\\"icon\\\":\\\"icon-briefcase\\\",\\\"parent\\\":\\\"2\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:21:04')
ERROR - 2018-02-27 03:21:34 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270321343386', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"23\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"8\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:21:34')
ERROR - 2018-02-27 03:22:03 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270322032077', '1', 'user-management/privilege_menu', 'Update', '{\\\"id\\\":\\\"5\\\",\\\"name\\\":\\\"Parameters\\\",\\\"description\\\":\\\"Manage Parameter\\\",\\\"url\\\":\\\"#\\\",\\\"icon\\\":\\\"icon-refresh\\\",\\\"parent\\\":\\\"0\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:22:03')
ERROR - 2018-02-27 03:22:29 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270322299182', '1', 'user-management/privilege_menu', 'Update', '{\\\"id\\\":\\\"13\\\",\\\"name\\\":\\\"User Type\\\",\\\"description\\\":\\\"Manage User Type\\\",\\\"url\\\":\\\"parameters\\\\/usertype\\\",\\\"icon\\\":\\\"icon-user-following\\\",\\\"parent\\\":\\\"5\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:22:29')
ERROR - 2018-02-27 03:22:48 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270322485187', '1', 'user-management/privilege_menu', 'Update', '{\\\"id\\\":\\\"33\\\",\\\"name\\\":\\\"Global Parameter\\\",\\\"description\\\":\\\"Manage Global Parameter\\\",\\\"url\\\":\\\"parameters\\\\/globalparameter\\\",\\\"icon\\\":\\\"icon-globe-alt\\\",\\\"parent\\\":\\\"5\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:22:48')
ERROR - 2018-02-27 03:24:14 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270324141429', '1', 'user-management/privilege_menu', 'Update', '{\\\"id\\\":\\\"5\\\",\\\"name\\\":\\\"Parameters\\\",\\\"description\\\":\\\"Manage Parameter\\\",\\\"url\\\":\\\"#\\\",\\\"icon\\\":\\\"icon-shield\\\",\\\"parent\\\":\\\"0\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:24:14')
ERROR - 2018-02-27 03:24:55 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270324554084', '1', 'user-management/privilege_menu', 'Update', '{\\\"id\\\":\\\"5\\\",\\\"name\\\":\\\"Parameters\\\",\\\"description\\\":\\\"Manage Parameter\\\",\\\"url\\\":\\\"#\\\",\\\"icon\\\":\\\"icon-shuffle\\\",\\\"parent\\\":\\\"0\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:24:55')
ERROR - 2018-02-27 03:25:42 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270325424775', '1', 'user-management/privilege_menu', 'Update', '{\\\"id\\\":\\\"5\\\",\\\"name\\\":\\\"Parameters\\\",\\\"description\\\":\\\"Manage Parameter\\\",\\\"url\\\":\\\"#\\\",\\\"icon\\\":\\\"icon-loop\\\",\\\"parent\\\":\\\"0\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:25:42')
ERROR - 2018-02-27 03:27:07 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270327076398', '1', 'user-management/privilege_menu', 'Save', '{\\\"id\\\":\\\"\\\",\\\"name\\\":\\\"Email\\\",\\\"description\\\":\\\"\\\",\\\"url\\\":\\\"parameters\\\\/email\\\",\\\"icon\\\":\\\"icon-envelope\\\",\\\"parent\\\":\\\"5\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Saving Data\\\",\\\"message\\\":\\\"Data has been saved.\\\"}', '::1', '1', '2018-02-27 03:27:07')
ERROR - 2018-02-27 03:27:27 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270327276718', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"35\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:27:27')
ERROR - 2018-02-27 03:27:31 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270327309633', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"35\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"2\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:27:30')
ERROR - 2018-02-27 03:28:28 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270328286166', '1', 'user-management/privilege_menu', 'Save', '{\\\"id\\\":\\\"\\\",\\\"name\\\":\\\"Email Templates\\\",\\\"description\\\":\\\"\\\",\\\"url\\\":\\\"parameters\\\\/emailtemplate\\\",\\\"icon\\\":\\\"icon-envelope-letter\\\",\\\"parent\\\":\\\"5\\\",\\\"status\\\":\\\"0\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Saving Data\\\",\\\"message\\\":\\\"Data has been saved.\\\"}', '::1', '1', '2018-02-27 03:28:28')
ERROR - 2018-02-27 03:28:41 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270328419612', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"35\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"8\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:28:41')
ERROR - 2018-02-27 03:28:45 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270328454535', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"36\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:28:45')
ERROR - 2018-02-27 03:28:57 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270328578188', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"36\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"2\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:28:57')
ERROR - 2018-02-27 03:29:05 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270329054436', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"36\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"2\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:29:05')
ERROR - 2018-02-27 03:29:22 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270329224289', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"36\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"4\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:29:22')
ERROR - 2018-02-27 03:29:27 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270329276282', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"36\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"4\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:29:27')
ERROR - 2018-02-27 03:29:33 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270329335023', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"36\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"2\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:29:33')
ERROR - 2018-02-27 03:29:38 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270329382241', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"36\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"8\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:29:38')
ERROR - 2018-02-27 03:31:05 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270331052566', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"36\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:31:05')
ERROR - 2018-02-27 03:31:09 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270331091194', '1', 'user-management/privilege_menu', 'Save', '{\\\"menu\\\":\\\"36\\\",\\\"privilege\\\":\\\"1\\\",\\\"access\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:31:09')
ERROR - 2018-02-27 03:31:15 --> Query error: Unknown column 'ip' in 'field list' - Invalid query: INSERT INTO `cms_action_history` (`id`, `id_user`, `url`, `actions`, `data`, `result`, `ip`, `entry_by`, `entry_time`) VALUES ('201802270331150928', '1', 'user-management/privilege_menu', 'Update', '{\\\"id\\\":\\\"36\\\",\\\"name\\\":\\\"Email Templates\\\",\\\"description\\\":\\\"\\\",\\\"url\\\":\\\"parameters\\\\/emailtemplate\\\",\\\"icon\\\":\\\"icon-envelope-letter\\\",\\\"parent\\\":\\\"5\\\",\\\"status\\\":\\\"1\\\"}', '{\\\"success\\\":true,\\\"title\\\":\\\"Updating Data\\\",\\\"message\\\":\\\"Data has been updated.\\\"}', '::1', '1', '2018-02-27 03:31:15')
ERROR - 2018-02-27 03:33:51 --> 404 Page Not Found: parameters/Email/index
